### PR TITLE
new classes; closes #241

### LINKED ISSUE #241: Increased and decreased terms for new rate subclasses
Related to #221 
We also need 'increased ...' and 'decreased ...' for the new rate subclasses (after PR #228 is merged)

 - increased rate of occurrence
 - increased rate of continuous process
 - decreased rate of occurrence
 - decreased rate of continuous process

For the new term definitions we can just add 'Increase in...' or 'Decrease in...' to the beginning of the text definitions for the rates.
Relationships can follow the same pattern as 'increased frequency' and 'decreased frequency'

### PR DESCRIPTION
**Pull request by mah11**
increased rate of occurrence PATO_0055003
decreased rate of occurrence PATO_0055004
increased rate of continuous process PATO_0055005
decreased rate of continuous process PATO_0055006

### CODE REVIEW

**Review by Clare72 — APPROVED** [review]
Looks good to me!

**Comment by matentzn** [comment]
I am happy for this to be merged, but I am very concerned that the textual definitions provided to explain how they are to be distinguished from other PATO classes...

I basically need to know when to use: "increased rate of occurrence" (of biological process) and when to use "increased occurrence" ([ols](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002052&viewMode=PreferredRoots&siblings=false)), or increased rate. 

Same with `decreased rate of continuous process`; when should I use that vs `decreased rate`. 

Generally I am a bit weary of having qualities that actually name the nature of the object in question (continuous process). Can we not find a label that really describes the quality without naming the applicability range? Something like "decreased output rate"?

**Comment by Clare72** [comment]
@matentzn - would you prefer the definitions from 'rate of occurence' and 'rate of continuous process' to be duplicated into these definitions as suggested in the [ticket](https://github.com/pato-ontology/pato/issues/241)?

I agree that 'occurrence' is not well defined, but perhaps this should have its own ticket.
I think these will autoclassify as subclasses of 'increased rate' and 'decreased rate'.

Is there a problem with this type of label? Why are you weary of it?
The purpose of these terms was to distinguish continuous (e.g. growth, motion) and repeated (e.g. heartbeats, wingbeats) processes (see #221) and I don't think 'decreased output rate' does that, unless you are suggesting 'decreased output rate of continuous process'(?)

**Comment by mah11** [comment]
@matentzn @Clare72 
For the terms in the PR I made the names match those used for the superclasses in #241, and followed the precedent of existing PATO text defs (which I admit was lazy ;) there are loads of other text defs that are similarly suboptimal).

I'm willing to have a better look at defs in the 'rate' and 'occurrence' areas and try to improve them, but it will have to wait a couple weeks (holiday coming up). In the meantime, I don't mind whether this PR gets merged in now or waits for further improvements.

I have a big chunk of work on FYPO that requires the distinctions that #221 and #241 are intended to make, so I have an interest in improving this part of PATO, as well as ideas how I'd go about it.

**Review by matentzn — APPROVED** [review]
Scratch what I was saying, I didnt know that you already hat the general (non-increased) qualities in PATO.. At some point someone needs to tell me really what all this things mean, but that is independent of this PR!

**Pull request merged**
