### PR TITLE
Fixes #267

### LINKED ISSUE #267: variability should be a direct subclass of PATO:Quality NOT process quality
The current location is causing many unsatisfiable classes:

image

### PR DESCRIPTION
**Pull request by dosumis**

### CODE REVIEW

**Comment by matentzn** [comment]
Just noting that this might not be sufficient:

```
[Term]
id: PATO:0001612
name: increased variability of color
def: "A variability of color which is relatively high." [PATO:GVG]
subset: value_slim
synonym: "high variability of color" EXACT []
is_a: PATO:0001615 ! variant color
is_a: PATO:0002304 ! increased process quality
is_a: PATO:0002305 ! increased object quality
intersection_of: PATO:0001615 ! variant color
intersection_of: increased_in_magnitude_relative_to PATO:0000461 ! normal
relationship: is_opposite_of PATO:0001613 ! decreased variability of color
```

**Comment by matentzn** [comment]
But once we know whether we can go with quality instead of process quality, we can fix the rest in an analogous fashion.

**Comment by dosumis** [comment]
Looks like there's a bunch of (formerly) inferred classifications that are also asserted.  Will delete.

**Comment by dosumis** [comment]
Have rather brutally paired down assertions on this branch.  Patterns need to be investigated in order to make sure intended inferences are present.  In this case, this will presumably be part of a bigger refactoring to work out the relationship between variability qualities and the qualities that vary.

**Comment by matentzn** [comment]
I have migrated your changes [here](https://github.com/pato-ontology/pato/pull/270), so closing this now.

**Pull request closed without merging**
