### PR TITLE
add new terms nuclear/cytoplasmic ratio

### LINKED ISSUE #343: New Term Request - nuclear/cytoplasmic ratio
cellular quality
.   .  nuclear/cytoplasmic ratio: 'A quality inhering in a cell by virtue of the ratio between the volume of its nucleus and the volume of its cytoplasm' [Wikipedia:https://en.wikipedia.org/wiki/NC_ratio]; Exact_synonym: "N:C ratio" [Wikipedia:https://en.wikipedia.org/wiki/NC_ratio]
.   .    .  high nuclear/cytoplasmic ratio:  'A quality inhering in a cell by virtue of the cell having a high nuclear/cytoplasmic ratio. [https://en.wikipedia.org/wiki/NC_ratio];  exact_synonym: "high N:C ratio"; Comment: TBA - context on what counts as high in the context of hematology.*

\* @addiehl  - can you reconcile https://en.wikipedia.org/wiki/NC_ratio & http://lymerick.net/blood-cells.pdf to write some guidance on what counts as high here?

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
and high nuclear/cytoplasmic ratio
closes #343

### CODE REVIEW

**Comment by dosumis** [comment]
@addiehl We need some text for what counts as a high N:C ratio.  @nicolevasilevsky - if no suggestion from Alex, I'd suggest going with 70% or higher based on the pdf

**Comment by nicolevasilevsky** [comment]
@dosumis I revised the comment

**Comment by nicolevasilevsky** [comment]
I updated the IDs for the new PATO terms, as the IDs were in use by other terms.

There a couple unexpected changes on the diff but I don't think they are an issue.

**Review by dosumis — DISMISSED** [review]

**Comment by nicolevasilevsky** [comment]
@dosumis, @addiehl do we need two approvals or can I merge this?

**Pull request merged**
