### PR TITLE
Mapped pato towards and pato correlates with to RO terms

### PR DESCRIPTION
**Pull request by shawntanzk**
Related to https://github.com/pato-ontology/pato/issues/454

### CODE REVIEW

**Comment by shawntanzk** [comment]
@matentzn - I somehow cant seem to find the imported RO terms in protege, was wondering if I was missing something? 

I basically changed the RO slim from .obo to .owl
refresh repo twice
and ran `sh run.sh make imports/ro_import.owl`

Could you help me with this please? Thanks!

**Comment by matentzn** [comment]
With base files you cannot refresh an individual import; you have to refresh the base module (merged_import.owl). 

```
sh run.sh make no-mirrors-refresh-merged
```

**Comment by shawntanzk** [comment]
```
shawntan@C02DW26DML87 ontology % sh run.sh make no-mirrors-refresh-merged 
pato.Makefile:10: warning: overriding recipe for target 'pato.obo'
Makefile:477: warning: ignoring old recipe for target 'pato.obo'
make: *** No rule to make target 'no-mirrors-refresh-merged'.  Stop.
```

seems to have an error unfortunately :(

**Comment by matentzn** [comment]
Have you merged master into this branch?

**Comment by matentzn** [comment]
```
no-mirror-refresh-merged
```

(no s in mirrors)

Now that you are a hacker, be brave and look into the `Makefile` when you get errors like that.. :)

**Comment by shawntanzk** [comment]
> Now that you are a hacker, be brave and look into the `Makefile` when you get errors like that.. :)

actually did - but stupidly searched for the the mirror with an s and couldn't find it and was very confused :p

**Review by matentzn — APPROVED** [review]
For total cleanliness of PR, reset ro import which does not need to be updated anymore:

```
git checkout master --  imports/ro_import.owl
```

**Review by matentzn — APPROVED** [review]

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
You can remove chris and Nicole from reviewers and add anita and ray instead

**Review by anitacaron — APPROVED** [review]

**Pull request merged**
