### PR TITLE
add new terms: diandrous and more

### LINKED ISSUE #257: NTR: Diandrous and monandrous
This will be tricky because diandrous and monandrous mean different things for plants and animals. How should we differentiate in the label?

Preferred Label
Diandrous
Monandrous

Definition
Diandrous (plant): having two stamens
Monandrous (plant): having one stamen
Diandrous (animal): possessing two different types of males
Monandrous (animal): having only one type of male

Parent Class
The plant terms should be subclasses of 'phenotypic sex'
the animal terms should be subclasses of 'mixed sex'

Attribution
http://orcid.org/0000-0002-2908-3327

Notes
There is also diandry: fertilization of an egg by two sperm.

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
monandrous
protogynous
protandrous
protogynous hermaphroditism
protandrous hermaphroditism
sequential hermaphrodite

close #257

this replaces https://github.com/pato-ontology/pato/pull/350

cc @matentzn

### CODE REVIEW

**Review by ramonawalls — COMMENTED** [review]
I fixed typo in `contamination`; change "entitt" to "entity".

Otherwise, this looks good to me.

**Review by ramonawalls — APPROVED** [review]

**Comment by nicolevasilevsky** [comment]
> I fixed typo in `contamination`; change "entitt" to "entity".

thanks @ramonawalls!

**Review by shawntanzk — APPROVED** [review]
@nicolevasilevsky I'm just going to put an approve review on this PR as it has been open for awhile and already has an approve review - in case you are just waiting for a 2nd approval for PATO to pass it. I don't know much about this area so don't know if there is something you wanted another reviewer to look at, if so, just ignore this approve review.

**Comment by nicolevasilevsky** [comment]
I'll go ahead and merge, thanks!

**Pull request merged**
