### PR TITLE
DO NOT MERGE: move PATO to ODK

### PR DESCRIPTION
**Pull request by dosumis**
See #269  DO NOT MERGE. MORE WORK NEEDED!

### CODE REVIEW

**Comment by matentzn** [comment]
I think this won't work like you intend it; you have basically half-way migrated everything to ODK now; which is good, but we still need to go all the way now. the problem is that pato.owl and pato.obo were originally constructed from the edit file without the imports, thereby conforming roughly to our "simple" artefacts; if you would release it as is now the imports would still be contained in the pato.owl/obo files. Maybe the best is to use this branch to move PATO over to ODK, which still begs the question whether the variability terms should be hotfixed elsewhere?

**Comment by dosumis** [comment]
> which still begs the question whether the variability terms should be hotfixed elsewhere?

Already done: https://github.com/pato-ontology/pato/pull/268

**Comment by matentzn** [comment]
Alright, we have a few small issues we will discuss on Thursday. Until then, it would be good to get some feedback from @cmungall and @balhoff  about the following two problems:

1) The is_opposite_of relation in the OBO edit file:
```
[Typedef]
id: is_opposite_of
name: is opposite of
xref: RO:0002604
is_metadata_tag: true
is_class_level: true
```

if you look in the edit file, the assertions are something like:

```
- relationship: is_opposite_of PATO:0000300 ! immobile
```

How is it possible (@cmungall ), given that is_opposite_of is an AP, that after pato-edit.obo --> OWL --> OBO we end up again with that `- relationship: is_opposite_of PATO:0000300 ! immobile`? rather than the below?

```
- relationship: is_opposite_of PATO:0000300 ! immobile
+ property_value: RO:0002604 PATO:0000300
```


Random observation of interest:
Pato base release looks almost exactly like the previous (pre-ODK) pato.obo. We could also use this as a solution if the above problem cant be resolved.

2) OBO foundrys simple artefact strips out intersection of and replaces them by `relationship:` tags (i.e. relax). Is this acceptable for the community (@balhoff @cmungall )?

**Comment by balhoff** [comment]
> `relationship: is_opposite_of PATO:0000300 ! immobile`

@matentzn I think this is appropriate. When the value of an annotation property is a term, it is in OBO as a relationship.

**Comment by matentzn** [comment]
So you are saying the roundtripping behaviour is a ROBOT bug @balhoff ?

**Comment by balhoff** [comment]
I don't think I follow yet. You say that the edit file has:

```
relationship: is_opposite_of PATO:0000300 ! immobile
```

and then after pato-edit.obo --> OWL --> OBO it ends up:

```
relationship: is_opposite_of PATO:0000300 ! immobile
```

That seems like a successful round trip?

**Comment by dosumis** [comment]
Ends up as 

+ property_value: RO:0002604 PATO:0000300

Because  RO:0002604 is an AP (in RO)

**Comment by cmungall** [comment]
David and Jim are correct. 

See 5.2.1 and 5.6 in http://owlcollab.github.io/oboformat/doc/obo-syntax.html

Note a feature of the spec is that there is more than one valid way to write an annotation assertion involving a non-literal in obo-format. The owlapi behavior is canonical. Perhaps not ideal and should be documented..

**Comment by balhoff** [comment]
I think I misunderstood what @matentzn said above. So the problem is that coming out of ROBOT it is stored as `property_value` but shouldn't be?

I just opened the pato.owl release with Protege and saved as OBO. I see relationships (correct). Then I passed this file through ROBOT convert and saved to OBO. Still see relationships. Same thing if I output to OWL and then re-read that and save as OBO.

**Comment by matentzn** [comment]
I dont know what happened here.. Maybe I was too rushed. It all works now; thanks for the input all. So what is remaining now is @cmungall comment:

> I note that pato.obo drops non-isa axioms. This may be fine for most users of this file, but the more consistent strategy would be to have the .obo and .owl be as isomoprhic as possible and make a pato-basic

First of all, and importantly we are not really dropping non-isas; it only looked like it.. What we do is relax the equivalents classes which pushes the contents from the `intersection_of:` tags into` relationship:` and then run reduce, which gets rid of most of them (all the logically redundant ones. 
 
Currently, we have that pato.owl corresponds to the "full" profile including imports; this suits the reasoning and OWL community. pato.obo however is used by the mods and various databases which find the contents of the "full" profile usually confusing (and by usually I mean all of them, unfortunately). Note that pato-full, pato-simple and pato-base of course exist already; the question is only what should be the defaults (pato.owl, pato.obo).

I guess we have three choices here:
A) we leave it like that (pato.owl is full, pato.obo is simple). Argument above. Downside: lack of isomorphic ness.
B) both are FULL. Downside: we alienate most users. That is a no-no IMHO.
C) both are simple. Downside: OWL users dont get the benefits of much of reasoning, lose logical definitions and more..

My weights are as follows: 51% A, 50% C, -1% B. Cast your votes :P

**Pull request merged**
