### PR TITLE
new terms; closes #254

### LINKED ISSUE #254: Add increased/decreased (broadened/narrowed?) spatial distribution of process
Subtypes of `spatial distribution of a process` (see #252)

Examples from @mah11:

E.g.

id: FYPO:0004322
name: decreased spatial extent of CENP-A containing nucleosome assembly
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which nucleosomes containing the histone H3 variant CenH3 (also called CENP-A; Cnp1 in S. pombe) are assembled over a smaller portion of the centromeric region of the chromosome than normal. CENP-A-containing nucleosomes are normally assembled into chromatin around centromeres, encompassing the central core and centromeric inner repeat regions." [GO:0034080, PMID:24710126, PomBase:mah, PomBase:vw]

id: FYPO:0004749
name: increased spatial extent of subtelomeric heterochromatin assembly
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which heterochromatin is assembled over a larger portion of the subtelomeric region of the chromosome than normal." [GO:0031509, PMID:25774602, PomBase:mah]

... or even ones like this?

id: FYPO:0005463
name: decreased spatial extent of interphase microtubule polymerization
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which cytoplasmic microtubule polymerization, i.e. the addition of tubulin dimers to the plus end of a cytoplasmic microtubule during interphase of the mitotic cell cycle, does not continue until microtubules reach the ends of the cell." [PMID:12894167, PomBase:mah]

We also have some 'normal' spatial extents in FYPO ...

### PR DESCRIPTION
**Pull request by mah11**
terms for increased & decreased spatial extent of a process; I went with the names and definitions I put in #254 

should we add any synonyms?

### CODE REVIEW

**Comment by mah11** [comment]
@dosumis
>  orcid should be orcid:nnn-nn... rather than full URL

OK; I saw it both ways in the obo file and didn't know which to follow. Thanks for the fixes.

@Clare72
> Shouldn't these be:
> 'spatial distribution of a process' and '<increased/decreased>_in magnitude_relative_to' some normal
> so that they will auto classify under '<increased/decreased> process quality'?

That does look sensible; thanks. But I'm new enough to this PATO editing that I don't actually know how to implement the suggestions ...

**Comment by dosumis** [comment]
Fixing both issues now.

**Comment by dosumis** [comment]
@Clare72 Fixed as requested.  Can you approve review if happy? Thanks!

**Comment by Clare72** [comment]
Your "orcid:" format should probably be propagated to the rest of the file, but not an issue for this PR.

**Comment by mah11** [comment]
thanks everyone!

**Pull request merged**
