### PR TITLE
Added bipolar morphology

### LINKED ISSUE #372: NTR: bipolar morphology
**Term:** 
bipolar morphology

**Definition:**
A cell morphology that inheres in neurons which have two principal dendrites, one ascending and one descending from the cell body, which begins to branch some distance from the soma. These dendrites have few spines, and branch in narrow fields. Bipolar morphology is distinguished from bitufted morphology by the long, unbranched, proximal portions of their principal dendrites and by the simplicity of the axonal plexus.
doi:10.1016/b978-0-12-369497-3.10004-4

**Parent Class:**
Cell Morphology #364

**Others:**
Neocortex Bipolar Cell: nifext:81; ILX:0107352. Bipolar Morphology: nifext:2; ILX:0101312    
ilxtr:BipolarPhenotype

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #372

### CODE REVIEW

**Review by patrick-lloyd-ray — COMMENTED** [review]
Do all cells with bipolar morphology have ascending and descending dendrites? For example, with bipolar cells in the retina it seems that they are bipolar because they have two sets of dendrites, but I don't know whether we would say that one set is ascending and one is descending.

**Comment by shawntanzk** [comment]
good point, I have removed the ascending and descending part - think it will be more generalizable now

**Review by dosumis — DISMISSED** [review]

**Review by dosumis — COMMENTED** [review]
I suspect this is still more a definition of neocortical bipolar neurons than a general one. I wonder whether this should be a simpler, broader definition, especially as a species neutral term - and one that is potentially applicable to neurons in many different locations. Wikipedia def might actually be a better guide: https://en.wikipedia.org/wiki/Bipolar_neuron#:~:text=A%20bipolar - although looking at that, it is hard to reconcile with the "two principal dendrites" definition here.  I wonder whether this is a case of the same terminology being used for quite different things in different contexts.

**Comment by shawntanzk** [comment]
> it is hard to reconcile with the "two principal dendrites" definition here. 

hmm good point, didn't even think too much about dendrites and axons. I guess that is taken more from retina cells which have no recognisable axon. How about we call it fibres and state that it could be axon on dendrite? something like: 

"A cell morphology that inheres in neurons which have two principal fibres (dendrites or axon) which begin to branch some distance from the soma. These fibres have few spines, and branch in narrow fields. Bipolar morphology is distinguished from bitufted morphology by the long, unbranched, proximal portions of their principal fibres and by the simplicity of the axonal plexus."

**Review by dosumis — APPROVED** [review]

**Pull request merged**
