### PR TITLE
reclassify magnitude and add def

### LINKED ISSUE #326: Reclassify: magnitude
Propose moving PATO_0002016 magnitude to child of 'process quality'
and need to define PATO_0002016 magnitude

suggested def: the size or extent of a process

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #326

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@dosumis @sbello could you please review this PR? thanks!

**Comment by sbello** [comment]
replied to @dosumis comment on #326 
Do we know if these terms are used by any ontology in a non-process related way?

**Comment by nicolevasilevsky** [comment]
@sbello it seems like there are still some open questions here. Should we just close this PR and I can redo the edits on another branch/PR if we reach a consensus.

**Comment by matentzn** [comment]
Will close this for now, as it will not be merged in this state!

**Pull request closed without merging**
