### PR TITLE
Add double type property violation

### PR DESCRIPTION
**Pull request by anitacaron**

### CODE REVIEW

**Review by matentzn — CHANGES_REQUESTED** [review]
Thanks! Looks good. Can you also run:

```
sh run.sh make update_repo
```

and commit the resulting files?

**Comment by matentzn** [comment]
Can you fix the error first?

**Comment by anitacaron** [comment]
Change from ERROR to WARN?

**Comment by matentzn** [comment]
No, better not. Does PATO have a CL import?

**Comment by anitacaron** [comment]
No. At least I don't see it here in the src/ontology/imports

**Comment by matentzn** [comment]
Hmmmm. OK.

What about this: 

- Set the error to WARN
- Copy error from http://robot.obolibrary.org/report_queries/missing_label and add same way you added the two-type error
- restrict that new error to look only at PATO_ classes

**Review by matentzn — APPROVED** [review]
Very well done! All good.

**Review by shawntanzk — APPROVED** [review]

**Pull request merged**
