### PR TITLE
Issue 312

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
@callahantiff could you review these definitions? Thanks!

related to https://github.com/obophenotype/human-phenotype-ontology/issues/3889

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
Per @dosumis suggestion on the HPO ticket (https://github.com/obophenotype/human-phenotype-ontology/issues/3889), I used the labels 'fractured, type'. Would it be okay if we labeled the terms as 'type fracture' instead? This would make more sense for the labels for uPheno terms (see PR for the new fracture pattern: https://github.com/obophenotype/upheno/pull/695)

**Comment by callahantiff** [comment]
@nicolevasilevsky - No problem! Just to confirm I am looking in the right place, I am reviewing the yaml file linked above?

**Comment by nicolevasilevsky** [comment]
@callahantiff could you review the text definitions here - these are the new fracture terms I added:
https://github.com/pato-ontology/pato/pull/313/files

(reviewing e yaml file linked above would be great too, thanks!)

**Comment by nicolevasilevsky** [comment]
Great, thank you Tiffany!

**Comment by matentzn** [comment]
I think the definitions and all that are great, but I am not sure about the labels.. We should really find a way to use either the "adjective" way of putting things across the board (fractured), or the nouny way (fracture). Right now its a wild mix (even in this PR - some terms are fracture, some fractured).  So, with the pattern in mind (fractured anatomical entity), what makes more sense as a default name to you all:

"fractured, impacted rib"
"impact fractured rib"
"fracture impact rib"
"impact fracture rib"

@callahantiff @nicolevasilevsky 

And whatever you chose, lets used that logic for all future term. I think the second is best, (impact fractured, linearly fractured, avulsion fractured, obliquely fractured etc..) but I am not a clinician :D.

**Comment by nicolevasilevsky** [comment]
We should use this form:
impact fractured rib

- [ ] need to fix the PATO terms

**Pull request merged**
