### PR TITLE
add new terms male with DSD and female with DSD

### LINKED ISSUE #482: Create terms 'male with DSD' and 'female with DSD'
Individuals with congenital physical disorders of sexual development (DSD; the term 'intersex' is more commonly known, but is a misnomer as people with DSD are not between sexes, a third sex or hermaphrodites) are not represented under male [PATO_0000384] or female [PATO_0000383]. These conditions can be valuable classifiers when relevant and are not the same as later changing natal/naturally-developed sexual characteristics (ie, castration [PATO_0002367] or spaying [PATO_0040020]).

Sources:
https://www.karger.com/Article/FullText/499274
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5866176/

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #482

### CODE REVIEW

**Review by balhoff — CHANGES_REQUESTED** [review]
@nicolevasilevsky could you pattern the definitions more after some of the other biological sex qualities? These versions describe an individual organism rather than quality of the organism.

**Comment by nicolevasilevsky** [comment]
@balhoff I updated the defs

**Review by balhoff — DISMISSED** [review]

**Comment by nicolevasilevsky** [comment]
@sbello or @dosumis could you please review this PR?

**Comment by nicolevasilevsky** [comment]
> So add the synonyms:
> male with differences of sexual differentiation
> female with differences of sexual differentiation

@sbello I added these synonyms. I will merge this when it passes.

**Pull request merged**
