### PR TITLE
Restructure amount

### LINKED ISSUE #554: restructure amount
From the UPheno call on Jan, 26 2024
Request changes to PATO

- [x] Create a quantitative branch
- [x] Move amount under this
- [x] Make concentration a child of amount
- [x] Remove reciprocal relation to ‘has number of’
- [x] Make has number of a child of amount

See minutes https://docs.google.com/document/d/1WrQanAMuccS-oaoAIb9yWQAd4Rvy3R3mU01v9wHbriM/edit?usp=sharing

### PR DESCRIPTION
**Pull request by rays22**
* Created a quantitative branch.
* Moved amount under this.
* Made concentration a child of amount.
* Removed reciprocal relation to ‘has number of’.
* Make has number of a child of amount.

If applied, this commit will fix #554.

### CODE REVIEW

**Review by sbello — CHANGES_REQUESTED** [review]
For the definition of quantitative, it might be better to avoid using 'amount' since that is a child term.
NLM has the definition of quantitative data "Quantitative data are [data](https://nnlm.gov/guides/data-glossary/data) represented numerically, including anything that can be counted, measured, or given a numerical value." https://www.nnlm.gov/guides/data-glossary/quantitative-data
Possibly we could adapt this to "a quality of an entity that can be represented numerically, including anything that can be counted, measured, or given a numerical value"
This could then be used as a model to define the qualitative branch ""a quality of an entity that is descriptive or observational, typically not represented numerically"  https://libguides.macalester.edu/c.php?g=527786&p=3608639 https://www.ncbi.nlm.nih.gov/books/NBK470395/ 
Defining qualitative wasn't part of this ticket but would be good to do.
Otherwise I think this looks good

**Comment by rays22** [comment]
> Quantitative data are [data](https://nnlm.gov/guides/data-glossary/data) represented numerically, including anything that can be counted, measured, or given a numerical value." https://www.nnlm.gov/guides/data-glossary/quantitative-data
> Possibly we could adapt this to "a quality of an entity that can be represented numerically, including anything that can be counted, measured, or given a numerical value"
> This could then be used as a model to define the qualitative branch ""a quality of an entity that is descriptive or observational, typically not represented numerically" https://libguides.macalester.edu/c.php?g=527786&p=3608639 https://www.ncbi.nlm.nih.gov/books/NBK470395/
> Defining qualitative wasn't part of this ticket but would be good to do.

Thanks @sbello , 
1.I have updated the text or the definition of 'quantitative', and 
2. added the definition to 'qualitative' that you suggest.

**Comment by sbello** [comment]
@rays22 please add the xrefs to the definitions for quantitative and qualitative so we can track where these came from (links in previous comment)

**Review by sbello — APPROVED** [review]
Looks good. Thansks Ray

**Pull request merged**
