### PR TITLE
2021-09-09 release

### PR DESCRIPTION
**Pull request by shawntanzk**
New Terms:
diandrous
monandrous
protogynous
protandrous
protogynous hermaphroditism
protandrous hermaphroditism
sequential hermaphrodite

Fixes:
Fixed spelling a error

Notes:
@ramonawalls adding you as a reviewer as there are a few terms with a created_by to your ORCID here
Might have issue with multiple def on "overlaps" as cyclical Uberon-PATO release and using IMP=false anyway -> if fails, I will go in and make edits, if not will refresh uberon after release happens after this release

### CODE REVIEW

**Comment by shawntanzk** [comment]
@matentzn release has obsolete term GO:0044464 in it from uberon import. 
```
shawntan@C02DW26DML87 pato % ! grep "! obsolete" pato-full.obo
is_a: GO:0044464 ! obsolete cell part
relationship: confers_advantage_in ENVO:00000568 ! obsolete aerial habitat
relationship: has_component GO:0044464 {minCardinality="2"} ! obsolete cell part
```
PATO doesn't have obsolete check I assume, shall I manually remove them or can we just wait of uberon release and refresh the imports?

**Comment by matentzn** [comment]
Annoying. 

Can you:
0) make new branch
1) open pato-edit in protege
2) delete `GO:0044464` and `ENVO:00000568`
3) make PR with just that change
4) once I approve it, run release again?

**Comment by shawntanzk** [comment]
> 2\. delete `GO:0044464` and `ENVO:00000568`

shall i delete just the axioms that use it, or should i go into the .obo file with atom and fully remove the terms too?

**Comment by matentzn** [comment]
Just the logical axioms is fine. Actually that would be best.

**Comment by shawntanzk** [comment]
Closing this and redo-ing (personally prefer to do it that way)

**Pull request closed without merging**
