### PR TITLE
create new terms PATO:0040030 and PATO:0040031

### LINKED ISSUE #300: NTR: width and length terms
- increased width and length
- decreased width and length

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #300

@matentzn can I create logical defs for these that are:
width
 and (decreased_in_magnitude_relative_to some normal)
and (length and (decreased_in_magnitude_relative_to some normal))

(I tested this and I actually get the correct inferences, but I'm not sure if this is correct)

### CODE REVIEW

**Comment by matentzn** [comment]
I think it’s fine as is.. if the human readable definitions are roughly in line with the definitions for increased width, it’s ok. I would mention that this quality requires both width and length to be decreased.

**Comment by matentzn** [comment]
(Just leave the logical definitions for now)

**Comment by dosumis** [comment]
I  think this is best  treated as a compound composition with two `has_part (inheres_in some ... ` clauses

**Comment by matentzn** [comment]
I thought so too! See our email trail about this with Chris and Jim! Chris suggested this!

**Comment by dosumis** [comment]
Scratch that - the compound PATO term is better. Much more sustainable.

**Comment by matentzn** [comment]
Actually: they can be classified more tightly:

`decreased width and length` subclass of `decreased width`
`decreased width and length` subclass of `decreased length`

same for the other one.

**Comment by nicolevasilevsky** [comment]
Let me know if any other actions are needed from me

**Pull request merged**
