### PR TITLE
add new term PATO:0040048 erythematous

### LINKED ISSUE #362: ntr: erythematous
see: https://github.com/obophenotype/human-phenotype-ontology/issues/5587#issuecomment-619379508

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #362

related: https://github.com/obophenotype/human-phenotype-ontology/issues/5587#issuecomment-761130787

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
To do: reclassify this term, determine the proper parent

**Comment by nicolevasilevsky** [comment]
@dosumis and @matentzn could one of you review this when you have a chance?
Thanks!

**Review by matentzn — APPROVED** [review]
Its fine by me! We have discussed many times that discolorations are covered by morphology, and there is little axiomatic risk and what you propose here otherwise.

**Review by pnrobinson — APPROVED** [review]

**Review by matentzn — APPROVED** [review]

**Review by dosumis — APPROVED** [review]
Looks good.  

Adding some notes here on  potential opportunity to improve axiomatistation (should be moved to ticket if general agreement):

* Consider grouping under skin quality? (with GCI indicating bearer must be region of skin?)
* Consider poss causal relationships -> Can we link to a circulation process?

**Pull request merged**
